Repository Warehousing/Warehousing, pull requests merged in 2019-02, with the labels that each got.

#52 Rework entity generation
  graphics/entity/warehouse-active-provider.png
  graphics/entity/warehouse-basic.png
  graphics/entity/warehouse-buffer.png
  graphics/entity/warehouse-passive-provider.png
  graphics/entity/warehouse-requester.png
  graphics/entity/warehouse-storage.png
  prototypes/entity.lua
Labels: internal

#57 New Crowdin translations
  locale/hu/locale.cfg
  locale/ko/locale.cfg
  locale/pt-BR/locale.cfg
  locale/zh-TW/locale.cfg
Labels: crowdin

#58 New Crowdin translations
  locale/ar/locale.cfg
  locale/ca/locale.cfg
  locale/cs/locale.cfg
  locale/da/locale.cfg
  locale/el/locale.cfg
  locale/fi/locale.cfg
  locale/fr/locale.cfg
  locale/he/locale.cfg
  locale/it/locale.cfg
  locale/nl/locale.cfg
  locale/no/locale.cfg
  locale/pt/locale.cfg
  locale/ro/locale.cfg
  locale/sr/locale.cfg
  locale/sv/locale.cfg
  locale/tr/locale.cfg
  locale/uk/locale.cfg
  locale/vi/locale.cfg
  locale/zh-CN/locale.cfg
Labels: crowdin

#56 Tweak storehouse icons to match warehouse icons
  graphics/icons/storehouse-active-provider.png
  graphics/icons/storehouse-buffer.png
  graphics/icons/storehouse-passive-provider.png
  graphics/icons/storehouse-requester.png
  graphics/icons/storehouse-storage.png
Labels: enhancement, graphics

#60 add startup setting, scale inventory icons
  locale/de/locale.cfg
  locale/en/locale.cfg
  prototypes/entity.lua
  settings.lua
Labels: enhancement

#61 New Crowdin translations
  locale/af/locale.cfg
  locale/ar/locale.cfg
  locale/ca/locale.cfg
  locale/cs/locale.cfg
  locale/da/locale.cfg
  locale/el/locale.cfg
  locale/es-ES/locale.cfg
  locale/fi/locale.cfg
  locale/fr/locale.cfg
  locale/he/locale.cfg
  locale/hu/locale.cfg
  locale/it/locale.cfg
  locale/ja/locale.cfg
  locale/ko/locale.cfg
  locale/nl/locale.cfg
  locale/no/locale.cfg
  locale/pl/locale.cfg
  locale/pt-BR/locale.cfg
  locale/pt/locale.cfg
  locale/ro/locale.cfg
  locale/ru/locale.cfg
  locale/sr/locale.cfg
  locale/sv/locale.cfg
  locale/tr/locale.cfg
  locale/uk/locale.cfg
  locale/vi/locale.cfg
  locale/zh-CN/locale.cfg
  locale/zh-TW/locale.cfg
Labels: crowdin

#59 Rebalance all the things
  Readme.md
  data-final-fixes.lua
  migrations/Warehousing_0.2.0.json
  migrations/Warehousing_0.2.0.lua
  prototypes/entity.lua
  prototypes/recipe.lua
  prototypes/technology.lua
Labels: enhancement

#63 Extra settings
  data-final-fixes.lua
  locale/en/locale.cfg
  prototypes/entity.lua
  settings.lua
Labels: enhancement

#62 New Crowdin translations
  locale/de/locale.cfg
  locale/es-ES/locale.cfg
Labels: crowdin
